import { FormEvent, ReactNode, useState } from 'react';
import { ArrowLeft, KeyRound, Mail } from 'lucide-react';
import { authErrorMessage, requestPasswordReset, resetPassword } from '../auth/authApi';

interface ForgotProps { onNavigateLogin: () => void; onNavigateReset: (token?: string) => void; }
export function ForgotPasswordScreen({ onNavigateLogin, onNavigateReset }: ForgotProps) {
  const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [devToken, setDevToken] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const result = await requestPasswordReset(email.trim()); setMessage(result.message); setDevToken(result.devToken ?? ''); } catch (cause) { setError(authErrorMessage(cause)); } finally { setBusy(false); } };
  return <AuthCard title="Recuperar acceso" subtitle="Te ayudaremos a restablecer tu contraseña de forma segura."><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium text-slate-700">Correo electrónico<input required type="email" value={email} onChange={e => setEmail(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-3" /></label>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <div role="status" className="space-y-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><p>{message}</p>{devToken && <><p className="text-xs">Token local de desarrollo:</p><code className="block break-all rounded bg-white p-2 text-xs">{devToken}</code><button type="button" onClick={() => onNavigateReset(devToken)} className="font-semibold underline">Continuar al cambio de contraseña</button></>}</div>}<button disabled={busy} className="w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? 'Enviando…' : 'Solicitar recuperación'}</button></form><button type="button" onClick={onNavigateLogin} className="mt-5 text-sm text-blue-600"><ArrowLeft className="mr-1 inline h-4 w-4" />Volver al inicio de sesión</button></AuthCard>;
}

export function ResetPasswordScreen({ initialToken, onNavigateLogin }: { initialToken?: string; onNavigateLogin: () => void }) {
  const [token, setToken] = useState(initialToken ?? ''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await resetPassword(token.trim(), password); setMessage('Contraseña actualizada. Ya puedes iniciar sesión.'); } catch (cause) { setError(authErrorMessage(cause)); } finally { setBusy(false); } };
  return <AuthCard title="Crear nueva contraseña" subtitle="El token es temporal y solo puede utilizarse una vez."><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium text-slate-700">Token de recuperación<textarea required value={token} onChange={e => setToken(e.target.value)} className="mt-1 min-h-20 w-full rounded-xl border border-slate-200 p-3 text-xs" /></label><label className="block text-sm font-medium text-slate-700">Nueva contraseña<input required minLength={8} type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-3" /></label>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}<button disabled={busy || Boolean(message)} className="w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? 'Guardando…' : 'Cambiar contraseña'}</button></form><button type="button" onClick={onNavigateLogin} className="mt-5 text-sm text-blue-600"><ArrowLeft className="mr-1 inline h-4 w-4" />Volver al inicio de sesión</button></AuthCard>;
}

function AuthCard({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <main className="w-full max-w-lg rounded-3xl border border-slate-100 bg-white p-8 shadow-xl"><div className="mb-7 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 text-white"><KeyRound className="h-5 w-5" /></div><div><strong className="block text-slate-900">Portal de Citas</strong><span className="text-xs uppercase text-slate-400"><Mail className="mr-1 inline h-3 w-3" />Acceso seguro</span></div></div><h1 className="text-2xl font-bold text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p>{children}</main>; }
