import { FormEvent, useEffect, useState } from 'react';
import { profileApi, catalogsApi, schedulingErrorMessage } from '../api/schedulingApi';
import type { CatalogItem, Profile } from '../types';

export function ProfilePanel() {
  const [profile, setProfile] = useState<Profile | null>(null); const [plans, setPlans] = useState<CatalogItem[]>([]); const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [phone, setPhone] = useState(''); const [planId, setPlanId] = useState(''); const [membershipNumber, setMembershipNumber] = useState(''); const [busy, setBusy] = useState(true); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = async () => { setBusy(true); setError(''); try { const [nextProfile, nextPlans] = await Promise.all([profileApi.read(), catalogsApi.insurancePlans()]); setProfile(nextProfile); setPlans(nextPlans); setFirstName(nextProfile.firstName); setLastName(nextProfile.lastName); setPhone(nextProfile.phone ?? ''); setPlanId(nextProfile.affiliation?.plan.id ?? ''); setMembershipNumber(nextProfile.affiliation?.membershipNumber ?? ''); } catch (cause) { setError(schedulingErrorMessage(cause)); } finally { setBusy(false); } };
  useEffect(() => { void load(); }, []);
  const update = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setMessage(''); setError(''); try { setProfile(await profileApi.update({ firstName, lastName, phone })); setMessage('Perfil actualizado.'); } catch (cause) { setError(schedulingErrorMessage(cause)); } finally { setBusy(false); } };
  const saveAffiliation = async () => { if (!planId) return; setBusy(true); setMessage(''); setError(''); try { const affiliation = await profileApi.setAffiliation(planId, membershipNumber); setProfile(current => current ? { ...current, affiliation } : current); setMessage('Afiliación actualizada.'); } catch (cause) { setError(schedulingErrorMessage(cause)); } finally { setBusy(false); } };
  const removeAffiliation = async () => { setBusy(true); try { await profileApi.removeAffiliation(); setProfile(current => current ? { ...current, affiliation: null } : current); setPlanId(''); setMembershipNumber(''); setMessage('Afiliación retirada.'); } catch (cause) { setError(schedulingErrorMessage(cause)); } finally { setBusy(false); } };
  if (busy && !profile) return <section className="rounded-3xl border border-slate-100 bg-white p-6"><p role="status" className="text-sm text-slate-500">Cargando perfil…</p></section>;
  return <section className="space-y-4 rounded-3xl border border-slate-100 bg-white p-6 shadow-sm"><div><h2 className="text-lg font-bold">Mi perfil</h2><p className="text-sm text-slate-500">Actualiza solo los datos de contacto permitidos.</p></div>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}{profile && <><form onSubmit={update} className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-600">Nombres<input value={firstName} onChange={e => setFirstName(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 text-sm" /></label><label className="text-xs text-slate-600">Apellidos<input value={lastName} onChange={e => setLastName(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 text-sm" /></label><label className="text-xs text-slate-600">Teléfono<input value={phone} onChange={e => setPhone(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 text-sm" /></label><div className="text-xs text-slate-500"><span className="block">Correo</span><strong className="mt-1 block text-sm text-slate-700">{profile.email}</strong><span className="block">Documento: {profile.documentType} {profile.documentNumber}</span></div><button disabled={busy} className="rounded-xl bg-blue-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50 sm:col-span-2">Guardar perfil</button></form><div className="border-t pt-4"><h3 className="font-semibold">Afiliación</h3><div className="mt-2 grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-600">Plan<select value={planId} onChange={e => setPlanId(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 text-sm"><option value="">Sin afiliación</option>{plans.map(plan => <option value={plan.id} key={plan.id}>{plan.name}</option>)}</select></label><label className="text-xs text-slate-600">Número (opcional)<input value={membershipNumber} onChange={e => setMembershipNumber(e.target.value)} className="mt-1 w-full rounded-xl border p-2.5 text-sm" /></label></div><div className="mt-3 flex gap-2"><button type="button" disabled={busy || !planId} onClick={() => void saveAffiliation()} className="rounded-xl bg-slate-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Guardar afiliación</button><button type="button" disabled={busy || !profile.affiliation} onClick={() => void removeAffiliation()} className="rounded-xl border border-slate-300 px-3 py-2 text-sm disabled:opacity-50">Retirar</button></div></div></>}</section>;
}
